export const legalServices: Record<LocaleKey, string[]> = {
  ar: [
    "القانون المدني",
    "القانون الجنائي",
    "القانون التجاري",
    "قانون الأحوال الشخصية",
    "قانون المواريث",
    "قانون العمل",
    "القانون الإداري",
    "قانون الاستثمار",
    "قانون العقارات",
    "قانون الشركات",
    "قانون الضرائب",
    "قانون البنوك",
    "قانون التأمين",
    "قانون الملكية الفكرية",
    "قانون البيئة",
    "قانون الإعلام",
  ],
  en: [
    "Civil Law",
    "Criminal Law",
    "Commercial Law",
    "Family Law",
    "Inheritance Law",
    "Labor Law",
    "Administrative Law",
    "Investment Law",
    "Real Estate Law",
    "Corporate Law",
    "Tax Law",
    "Banking Law",
    "Insurance Law",
    "Intellectual Property Law",
    "Environmental Law",
    "Media Law",
  ],
  fr: [
    "Droit Civil",
    "Droit Pénal",
    "Droit Commercial",
    "Droit de la Famille",
    "Droit des Successions",
    "Droit du Travail",
    "Droit Administratif",
    "Droit d'Investissement",
    "Droit Immobilier",
    "Droit des Sociétés",
    "Droit Fiscal",
    "Droit Bancaire",
    "Droit des Assurances",
    "Droit de la Propriété Intellectuelle",
    "Droit de l'Environnement",
    "Droit des Médias",
  ],
};

export const titleMap: Record<LocaleKey, string> = {
  ar: "مكتب البنا للمحاماة",
  en: "Elbanna Law Firm",
  fr: "Cabinet d'avocats Elbanna",
};

export const openGraphLinks = {
  facebook: "https://www.facebook.com/AhmedElbannaLawyer",
  linkedin: "https://www.linkedin.com/company/ahmed-elbanna-lawyer-369527297",
  instagram: "https://www.instagram.com/ahmed_elbanna_lawyer",
  youtube: "https://www.youtube.com/@ahmed-elbanna1",
  tiktok: "https://www.tiktok.com/@ahmedelbanna65",
};
